### ISSUE TITLE
Pragha 1.4.0

### ISSUE THREAD

**Issue by matiasdelellis** [pragha-music-player/pragha#106]
### TODO:
- [ ] Merge WIP/Ampache branch.
 - [x] Sincronize with a ampache server.
 - [ ] Fix ping to server.
 - [ ] Remove Auth on ampaches URL.
 - [ ] Ensure SSL work..
- [ ] Use new PraghaBackgroundTaskWidgets to all tasks.
 - [x] Amapche plugin.
 - [x] Local colection.
 - [x] AcoustID plugin.
 - [x] TuneIn plugin.
 - [x] Removable plugin.
 - [ ] Cdrom plugin.
 - [ ] MTP device plugin.
 - [ ] DLNA renderer plugin.
 - [ ] Last-fm plugin.
 - [ ] Song-Info plugin.
- [ ] Fix Lastfm plugin.
 - [ ] Bad correction sugestions. Issue #93 
 - [ ] Find similar songs suggests hidden music collections.
- [ ] Fix DLNA server plugin.
- [ ] Fix DLNA renderer plugin.
- [ ] Toolbar shows 00:60 instead of 01:00. Issue #103 
- [ ] Port the rest of menues to GAction.
- [ ] Move minimun Gtk version to 3.14
- [ ] Fixes CSS on GTK 3.20
- [ ] Write release Notes.

**Comment by gogron** [comment]
have you thought of adding cue sheet playing support? it was the only deal breaker for me even though pragha is awesome and comes with xfce. would it be possible to implement as a plugin?

**Comment by matiasdelellis** [comment]
Hi @gogron 

> have you thought of adding cue sheet playing support?

It was something that was repeatedly requested.. and therefore is in plans. .. :wink: However do not expect it in a short time.. :disappointed: 

> it was the only deal breaker for me even though pragha is awesome and comes with xfce.

Many thanks!. :smiley: 
Although very focused on the is not part of xfce, .. :wink: 

> would it be possible to implement as a plugin?

For now no .. Other changes are needed, and after 1.4 there are other priorities for 1.6.. Sorry..  :persevere:

**Comment by LazyKent** [comment]
Please update.
Looks mostly complete.

**Comment by gftg85** [comment]
Do you have any plans to release it still in 2018?  That would be nice from a Debian perspective, because I could probably make it ready for the Buster release (Debian 10).

**Comment by matiasdelellis** [comment]
There are still some things to complete before release 1.4.. These days I updated this state.. :disappointed: 

On the other hand, I plan to release a version 1.3.4 soon, with many backports of 1.4 branch.. I suppose that would be better for the Debian standards .. :wink:
